cc_library(
  name = "core",
  srcs = ["core.cc"],
  hdrs = ["core.h"],
  deps = [
    "//proto:beamer_cfg_cc_proto",
    "//proto:beamer_out_cc_proto",
    "//gsl"
  ],
  visibility = ["//domain:__pkg__"]
)